const initialState = {
  nameUser: '',
  lastName: '',
  city: '',
  dateOfBirth: '',
  stateId: '',
  mail: '',
  backupMail: '',
  phone: '',
  backupPhone: '',
  urlLinkedin: '',
  urlPortfolio: '',
  urlRrss: '',
  fullTime: '',
  partTime: '',
  firstJob: '',
  practice: '',

  abautMe: '',
  nameInstitution: '',
  educationTitle: '',
  educationSince: '',
  educationUntil: '',
  educationDescription: '',
  educationArea: '',
  nameWorkInstitution: '',
  workTitle: '',
  workSince: '',
  workUntil: '',
  workDescription: '',
  workArea: '',
};

export default initialState;
